# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# IAR sab 13MAY2023
# código original
# trigger:
# - main

# pool:
#   vmImage: ubuntu-latest

# variables:
#   buildConfiguration: 'Release'

# steps:
# - script: dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'

  trigger:
  - '*'
  
  pool:
    vmImage: ubuntu-latest
  
  variables:
    buildConfiguration: 'Release'
    wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
    dotnetSdkVersion: '6.x'
  
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET SDK $(dotnetSdkVersion)'
    inputs:
      packageType: sdk
      version: '$(dotnetSdkVersion)'
  
  - task: Npm@1
    displayName: 'Run npm install'
    inputs:
      verbose: false
  
  - script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
    displayName: 'Compile Sass assets'
  
  - task: gulp@1
    displayName: 'Run gulp tasks'
  
  - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
    displayName: 'Write build info'
    workingDirectory: $(wwwrootDir)
  
  - task: DotNetCoreCLI@2
    displayName: 'Restore project dependencies'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
  
  - task: DotNetCoreCLI@2
    displayName: 'Build the project - $(buildConfiguration)'
    inputs:
      command: 'build'
      arguments: '--no-restore --configuration $(buildConfiguration)'
      projects: '**/*.csproj'

# Se agregó estas líneas para una 2a compilación y publicarla. IAR sab 13MAY2023
  - task: DotNetCoreCLI@2
    displayName: 'Publish the project - $(buildConfiguration)'
    inputs:
        command: 'publish'
        projects: '**/*.csproj'
        publishWebProjects: false
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: true
  ##########
  
  # Se agregó estas líneas para usar plantilla. IAR sab 13MAY2023
  - template: templates/build.yml
    parameters:
      buildConfiguration: 'Debug'
      
  - template: templates/build.yml
    parameters:
      buildConfiguration: 'Release'
  ##########
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    condition: succeeded()